#if defined(UV_CHANNEL_0)
#define TARGET_UV_CHANNEL TEXCOORD0
#elif defined(UV_CHANNEL_1)
#define TARGET_UV_CHANNEL TEXCOORD1
#elif defined(UV_CHANNEL_2)
#define TARGET_UV_CHANNEL TEXCOORD2
#elif defined(UV_CHANNEL_3)
#define TARGET_UV_CHANNEL TEXCOORD3
#elif defined(UV_CHANNEL_4)
#define TARGET_UV_CHANNEL TEXCOORD4
#elif defined(UV_CHANNEL_5)
#define TARGET_UV_CHANNEL TEXCOORD5
#elif defined(UV_CHANNEL_6)
#define TARGET_UV_CHANNEL TEXCOORD6
#elif defined(UV_CHANNEL_7)
#define TARGET_UV_CHANNEL TEXCOORD7
#else
#define TARGET_UV_CHANNEL TEXCOORD0
#endif
